SELECT OWNER FROM ALL_TABLES
WHERE OWNER LIKE('%STAGE%');

SELECT distinct COUNT(TABLE_NAME) FROM ALL_TABLES
WHERE OWNER LIKE('STAGE');

SELECT COUNT(TABLE_NAME) FROM ALL_TABLES
WHERE OWNER LIKE('ODS');

SELECT CONCAT( 'SELECT '|| TABLE_NAME||' AS TABLA',', COUNT(*) AS CANTIDAD FROM '||OWNER||'.'||table_name||' UNION' ) FROM ALL_TABLES
WHERE OWNER LIKE('STAGE') ORDER BY (TABLE_NAME) ASC;


