--CLIENTE
select COUNT(*)
from cliente.CLIENTE CL
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND (RM.FECHA<=TO_DATE('29/10/2015')) AND CL.RUT=RM.RUTCLIENTE )
order by CL.RUT;

--ACTIVIDADDEPENDIENTE

SELECT COUNT(*)
FROM CLIENTE.ActividadDependiente AD
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND (RM.FECHA<=TO_DATE('29/10/2015'))AND AD.RUTCLIENTE=RM.RUTCLIENTE )
order by AD.RUTCLIENTE;

--ACTIVIDADINDEPENDIENTE
SELECT COUNT(*)
FROM CLIENTE.ActividadINDependiente AI
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015') AND AI.RUTCLIENTE=RM.RUTCLIENTE )
order by AI.RUTCLIENTE;

--AFILIACIONEMAILING
select COUNT(*)
from CLIENTE.afiliacionemailing AF
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015')AND AF.RUT=RM.RUTCLIENTE )
order by AF.RUT;

--CONYUGE
select COUNT(*)
from cliente.conyuge cy
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015') AND cy.RUTCLIENTE=RM.RUTCLIENTE )
order by cy.RUTCLIENTE;

--CORREOELECTRONICO
SELECT COUNT(*)
FROM CLIENTE.CORREOELECTRONICO CE
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015') AND CE.RUTCLIENTE=RM.RUTCLIENTE )
order by CE.RUTCLIENTE;

--DIRECCION
select *
from cliente.direccion CD
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015') AND CD.RUTCLIENTE=RM.RUTCLIENTE )
order by CD.RUTCLIENTE;

--IDENTIFICACIONCLIENTE
SELECT COUNT(*)
 FROM CLIENTE.IDENTIFICACIONCLIENTE CL
INNER JOIN  CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015') AND CL.RUTCLIENTE=RM.RUTCLIENTE)
order by CL.RUTCLIENTE;

--SOL_ACTIVIDADDEPENDIENTE
SELECT COUNT(*)
FROM EVALUACION.SOL_ACTIVIDADDEPENDIENTE SAD
INNER JOIN  EVALUACION.SOL_HISTORIA SH ON (SH.FECHAHORA>=TO_DATE('06/09/2005')AND SH.FECHAHORA<=TO_DATE('29/10/2015')AND SAD.SOLICITUD=SH.SOLICITUD)
order by SAD.SOLICITUD;

--SOL_CLIENTE
select COUNT(*)
from EVALUACION.SOL_CLIENTE SC
INNER JOIN EVALUACION.SOL_HISTORIA EH ON (EH.FECHAHORA>=TO_DATE('06/09/2005')AND EH.FECHAHORA<=TO_DATE('29/10/2015') AND SC.SOLICITUD=EH.SOLICITUD )
order by SC.SOLICITUD;

--SOL_EVALUACION
select COUNT(*)
from EVALUACION.sol_evaluacion E
INNER JOIN  EVALUACION.SOL_HISTORIA SH ON (SH.FECHAHORA>=TO_DATE('06/09/2005')AND SH.FECHAHORA<=TO_DATE('29/10/2015') AND E.SOLICITUD=SH.SOLICITUD)
order by E.SOLICITUD;

--SOL_FINANCIAMIENTOCMR
SELECT COUNT(*)
FROM EVALUACION.SOL_FINANCIAMIENTOCMR F
INNER JOIN  EVALUACION.SOL_HISTORIA SH ON (SH.FECHAHORA>=TO_DATE('06/09/2005')AND SH.FECHAHORA<=TO_DATE('29/10/2015') AND F.SOLICITUD=SH.SOLICITUD)
order by F.SOLICITUD;

--SOL_HISTORIA
SELECT COUNT(*)
FROM EVALUACION.SOL_HISTORIA
WHERE FECHAHORA>=TO_DATE('06/09/2005') AND FECHAHORA<=TO_DATE('29/10/2015');

--SOL_IDENTIFICACIONCLIENTE
SELECT COUNT(*)
FROM EVALUACION.SOL_IDENTIFICACIONCLIENTE SIC
INNER JOIN  EVALUACION.SOL_HISTORIA SH ON (SH.FECHAHORA>=TO_DATE('06/09/2005')AND SH.FECHAHORA<=TO_DATE('29/10/2015') AND SIC.SOLICITUD=SH.SOLICITUD)
order by SIC.SOLICITUD;

--SOL_SITUACIONLABORAL
SELECT COUNT(*)
FROM EVALUACION.SOL_SITUACIONLABORAL SL
INNER JOIN  EVALUACION.SOL_HISTORIA SH ON (SH.FECHAHORA>=TO_DATE('06/09/2005')AND SH.FECHAHORA<=TO_DATE('29/10/2015') AND SL.SOLICITUD=SH.SOLICITUD)
order by SL.SOLICITUD,SL.TIPOEMPLEO;

--SOL_SOLICITUD
SELECT COUNT(*)
FROM EVALUACION.SOL_SOLICITUD SS
INNER JOIN  EVALUACION.SOL_HISTORIA SH ON (SH.FECHAHORA>=TO_DATE('06/09/2005')AND SH.FECHAHORA<=TO_DATE('29/10/2015') AND SS.NUMERO=SH.SOLICITUD)
order by SS.NUMERO;

--SOL_TARJETACREDITOBANCARIA
select COUNT(*)
from evaluacion.sol_tarjetacreditobancaria tcb
INNER JOIN  EVALUACION.SOL_HISTORIA SH ON (SH.FECHAHORA>=TO_DATE('06/09/2005')AND SH.FECHAHORA<=TO_DATE('29/10/2015') AND tcb.SOLICITUD=SH.SOLICITUD)
order by tcb.SOLICITUD,tcb.NUMERO;

--TELEFONO
SELECT COUNT(*)
FROM CLIENTE.TELEFONO TE
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015') AND TE.RUTCLIENTE=RM.RUTCLIENTE )
order by TE.RUTCLIENTE;

--VIVIENDA
SELECT COUNT(*)
FROM CLIENTE.VIVIENDA VI
INNER JOIN CLIENTE.REGISTROMODIFICACION RM ON (RM.FECHA>=TO_DATE('06/09/2005')AND RM.FECHA<=TO_DATE('29/10/2015') AND VI.RUTCLIENTE=RM.RUTCLIENTE )
order by VI.RUTCLIENTE;