SELECT 'AUTORIZACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.AUTORIZACION
UNION
SELECT 'BENEFICIARIOCUENTATARJETA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.BENEFICIARIOCUENTATARJETA
UNION
SELECT 'BENEFICIARIOCUENTATARJ_MONEDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.BENEFICIARIOCUENTATARJ_MONEDA
UNION
SELECT 'CALENDARIOGRUPOPROCESO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CALENDARIOGRUPOPROCESO
UNION
SELECT 'CONCECONOMICO_DETALLECUOTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONCECONOMICO_DETALLECUOTA
UNION
SELECT 'CONCECONOMICO_EXTRACTOCREDITO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONCECONOMICO_EXTRACTOCREDITO
UNION
SELECT 'CONCECONOMICO_PENDIENTEIMPAGO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONCECONOMICO_PENDIENTEIMPAGO
UNION
SELECT 'CONCECONOMICO_TIPOFACTURA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONCECONOMICO_TIPOFACTURA
UNION
SELECT 'CONTCUENTATARJETA_CLIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONTCUENTATARJETA_CLIENTE
UNION
SELECT 'CONTCUENTATARJETA_ENTIBLOQUEO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONTCUENTATARJETA_ENTIBLOQUEO
UNION
SELECT 'CONTCUENTATARJETA_ENTIMONEDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONTCUENTATARJETA_ENTIMONEDA
UNION
SELECT 'CONTIMPAG_TIPOLINEA_TIPIMPORTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONTIMPAG_TIPOLINEA_TIPIMPORTE
UNION
SELECT 'CONTRATOCUENTATARJETA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONTRATOCUENTATARJETA
UNION
SELECT 'CONTRATOIMPAGADO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CONTRATOIMPAGADO
UNION
SELECT 'CUOTAFINANCIADA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.CUOTAFINANCIADA
UNION
SELECT 'DETALLECUOTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.DETALLECUOTA
UNION
SELECT 'ENTIDADBLOQUEO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.ENTIDADBLOQUEO
UNION
SELECT 'ENTIDADTIPOCUOTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.ENTIDADTIPOCUOTA
UNION
SELECT 'EXTRACTOCREDITO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.EXTRACTOCREDITO
UNION
SELECT 'EXTRACTO_TIPOLINEA_TIPOIMPORTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.EXTRACTO_TIPOLINEA_TIPOIMPORTE
UNION
SELECT 'FACTURASCOMERCIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.FACTURASCOMERCIO
UNION
SELECT 'GRUPOPROCESO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.GRUPOPROCESO
UNION
SELECT 'HISTORICOMODIFICACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.HISTORICOMODIFICACION
UNION
SELECT 'HISTORICOPAGO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.HISTORICOPAGO
UNION
SELECT 'LIMITEREFERENCIALINEACONTRATO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.LIMITEREFERENCIALINEACONTRATO
UNION
SELECT 'MENSAJEREDTIPOFACTURA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.MENSAJEREDTIPOFACTURA
UNION
SELECT 'MOTIVOBAJA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.MOTIVOBAJA
UNION
SELECT 'MOVIMIENTOEXTRACTOCREDITO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.MOVIMIENTOEXTRACTOCREDITO
UNION
SELECT 'MOVIMIENTOIMPAGADO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.MOVIMIENTOIMPAGADO
UNION
SELECT 'OPERACIONESCUOTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.OPERACIONESCUOTA
UNION
SELECT 'PROCESO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.PROCESO
UNION
SELECT 'PROCESOSTARJETA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.PROCESOSTARJETA
UNION
SELECT 'PRODUCTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.PRODUCTO
UNION
SELECT 'RECIBO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.RECIBO
UNION
SELECT 'RECIBOIMPAGADO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.RECIBOIMPAGADO
UNION
SELECT 'RECIBOIMPAGADO_TIPOIMPORTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.RECIBOIMPAGADO_TIPOIMPORTE
UNION
SELECT 'REFERENCIATIPOLINEACONTRATO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.REFERENCIATIPOLINEACONTRATO
UNION
SELECT 'REGIMENFISCAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.REGIMENFISCAL
UNION
SELECT 'TARJETACREDITO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.TARJETACREDITO
UNION
SELECT 'TIPOIMPUESTO_REGIMENFISCAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.TIPOIMPUESTO_REGIMENFISCAL
UNION
SELECT 'TIPOLINEACREDITO_PRODUCTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.TIPOLINEACREDITO_PRODUCTO
UNION
SELECT 'TRAMTIPOCOMPRACUOTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.TRAMTIPOCOMPRACUOTA
UNION
SELECT 'TRAMTIPOCOMPRACUOTA_ENTIMONEDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_TARJETACREDITO.TRAMTIPOCOMPRACUOTA_ENTIMONEDA
UNION
SELECT 'CANALVENTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.CANALVENTA
UNION
SELECT 'CONSIGNATARIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.CONSIGNATARIO
UNION
SELECT 'EMPRESAGRUPOFALABELLA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.EMPRESAGRUPOFALABELLA
UNION
SELECT 'ESTADOSOLICITUDEVALUACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.ESTADOSOLICITUDEVALUACION
UNION
SELECT 'ESTADOSOLICITUDWORKFLOW' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.ESTADOSOLICITUDWORKFLOW
UNION
SELECT 'EVALUACIONPOLITICACMR' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.EVALUACIONPOLITICACMR
UNION
SELECT 'GRUPO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.GRUPO
UNION
SELECT 'INSTITUCION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.INSTITUCION
UNION
SELECT 'MARCACLASE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.MARCACLASE
UNION
SELECT 'MOTIVOTRAMITEAUTOMATICO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.MOTIVOTRAMITEAUTOMATICO
UNION
SELECT 'OFERTASCLIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.OFERTASCLIENTE
UNION
SELECT 'PERFILRIESGO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.PERFILRIESGO
UNION
SELECT 'PROMOTOR' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.PROMOTOR
UNION
SELECT 'PROMOTOR_CONSIGNATARIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.PROMOTOR_CONSIGNATARIO
UNION
SELECT 'SOLICITUD' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUD
UNION
SELECT 'SOLICITUDACTIDEPENDIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDACTIDEPENDIENTE
UNION
SELECT 'SOLICITUDACTIESTUDIANTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDACTIESTUDIANTE
UNION
SELECT 'SOLICITUDACTIINDEPENDIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDACTIINDEPENDIENTE
UNION
SELECT 'SOLICITUDACTIRENTISTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDACTIRENTISTA
UNION
SELECT 'SOLICITUDCLIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDCLIENTE
UNION
SELECT 'SOLICITUDCLIENTEIDENTIFICACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDCLIENTEIDENTIFICACION
UNION
SELECT 'SOLICITUDDOCUMENTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDDOCUMENTO
UNION
SELECT 'SOLICITUDDOCUMENTODESEMBOLSO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDDOCUMENTODESEMBOLSO
UNION
SELECT 'SOLICITUDEVALUACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDEVALUACION
UNION
SELECT 'SOLICITUDFINANCIAMIENTOCMR' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDFINANCIAMIENTOCMR
UNION
SELECT 'SOLICITUDHISTORIA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDHISTORIA
UNION
SELECT 'SOLICITUDSITUACIONLABORAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDSITUACIONLABORAL
UNION
SELECT 'SOLICITUDTARJCREDITOBANCARIA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.SOLICITUDTARJCREDITOBANCARIA
UNION
SELECT 'TIPOCONSIGNATARIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.TIPOCONSIGNATARIO
UNION
SELECT 'TIPOCREDITO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.TIPOCREDITO
UNION
SELECT 'TIPOGRUPO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.TIPOGRUPO
UNION
SELECT 'TIPOSOLICITUD' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_SOLICITUD.TIPOSOLICITUD
UNION
SELECT 'ACTIVIDAD' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ACTIVIDAD
UNION
SELECT 'ACTIVIDADDEPENDIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ACTIVIDADDEPENDIENTE
UNION
SELECT 'ACTIVIDADECONOMICA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ACTIVIDADECONOMICA
UNION
SELECT 'ACTIVIDADESTUDIANTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ACTIVIDADESTUDIANTE
UNION
SELECT 'ACTIVIDADINDEPENDIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ACTIVIDADINDEPENDIENTE
UNION
SELECT 'ACTIVIDADRENTISTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ACTIVIDADRENTISTA
UNION
SELECT 'AFILIACIONEMAILING' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.AFILIACIONEMAILING
UNION
SELECT 'BLOQUEO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.BLOQUEO
UNION
SELECT 'CARGOFUNCIONARIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.CARGOFUNCIONARIO
UNION
SELECT 'CENTROFINANCIERO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.CENTROFINANCIERO
UNION
SELECT 'CLASIFICACIONSBS' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.CLASIFICACIONSBS
UNION
SELECT 'CLIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.CLIENTE
UNION
SELECT 'COMPORTAMIENTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.COMPORTAMIENTO
UNION
SELECT 'CONYUGE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.CONYUGE
UNION
SELECT 'DATOADICIONALPERSONA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.DATOADICIONALPERSONA
UNION
SELECT 'DATOSTIPOCLIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.DATOSTIPOCLIENTE
UNION
SELECT 'EMPRESA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.EMPRESA
UNION
SELECT 'ESPECIALIDADEDUCACIONAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ESPECIALIDADEDUCACIONAL
UNION
SELECT 'ESTABLECIMIENTOEDUCACIONAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ESTABLECIMIENTOEDUCACIONAL
UNION
SELECT 'FOLIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.FOLIO
UNION
SELECT 'GIROEMPRESA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.GIROEMPRESA
UNION
SELECT 'HABITOPAGO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.HABITOPAGO
UNION
SELECT 'IDENTIFICACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.IDENTIFICACION
UNION
SELECT 'NIVELEDUCACIONAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.NIVELEDUCACIONAL
UNION
SELECT 'OPERACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.OPERACION
UNION
SELECT 'OPERACION_ACCESO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.OPERACION_ACCESO
UNION
SELECT 'PERIODICIDADINGRESO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.PERIODICIDADINGRESO
UNION
SELECT 'PERSONA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.PERSONA
UNION
SELECT 'PERSONAJURIDICA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.PERSONAJURIDICA
UNION
SELECT 'PERSONA_MEDIOSCONTACTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.PERSONA_MEDIOSCONTACTO
UNION
SELECT 'PERSONANATURAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.PERSONANATURAL
UNION
SELECT 'PERSONA_ROL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.PERSONA_ROL
UNION
SELECT 'PROVINCIA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.PROVINCIA
UNION
SELECT 'REGIMENMATRIMONIAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.REGIMENMATRIMONIAL
UNION
SELECT 'REGIMENTRIBUTARIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.REGIMENTRIBUTARIO
UNION
SELECT 'ROL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.ROL
UNION
SELECT 'SEXO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.SEXO
UNION
SELECT 'SITUACIONLABORAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.SITUACIONLABORAL
UNION
SELECT 'TABLAORIGEN' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TABLAORIGEN
UNION
SELECT 'TIPOBLOQUEOIDENTIFICACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOBLOQUEOIDENTIFICACION
UNION
SELECT 'TIPOCENTROFINANCIERO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOCENTROFINANCIERO
UNION
SELECT 'TIPOCLIENTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOCLIENTE
UNION
SELECT 'TIPODIRECCION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPODIRECCION
UNION
SELECT 'TIPODOCUMENTOIDENTIFICACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPODOCUMENTOIDENTIFICACION
UNION
SELECT 'TIPOEDIFICACIONVIVIENDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOEDIFICACIONVIVIENDA
UNION
SELECT 'TIPOEMPLEO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOEMPLEO
UNION
SELECT 'TIPOEMPRESA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOEMPRESA
UNION
SELECT 'TIPOINGRESO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOINGRESO
UNION
SELECT 'TIPOINSTITUCIONEDUCACIONAL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOINSTITUCIONEDUCACIONAL
UNION
SELECT 'TIPOMEDIOSCONTACTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOMEDIOSCONTACTO
UNION
SELECT 'TIPOMONTORENTA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOMONTORENTA
UNION
SELECT 'TIPOSITUACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.TIPOSITUACION
UNION
SELECT 'USUARIO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.USUARIO
UNION
SELECT 'VIVIENDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_PERSONA.VIVIENDA
UNION
SELECT 'CARGO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.CARGO
UNION
SELECT 'CENTROCOSTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.CENTROCOSTO
UNION
SELECT 'CONCEPTOECONOMICO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.CONCEPTOECONOMICO
UNION
SELECT 'DEPARTAMENTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.DEPARTAMENTO
UNION
SELECT 'DIRECCION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.DIRECCION
UNION
SELECT 'DISTRITO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.DISTRITO
UNION
SELECT 'ENTIDAD' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.ENTIDAD
UNION
SELECT 'ENTIDADFRANQUICIA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.ENTIDADFRANQUICIA
UNION
SELECT 'ENTIDADMARCATIPOTARJETA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.ENTIDADMARCATIPOTARJETA
UNION
SELECT 'ENTIDADMONEDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.ENTIDADMONEDA
UNION
SELECT 'ESTADOCIVIL' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.ESTADOCIVIL
UNION
SELECT 'FRANQUICIA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.FRANQUICIA
UNION
SELECT 'IDIOMA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.IDIOMA
UNION
SELECT 'MARCATARJETA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.MARCATARJETA
UNION
SELECT 'MONEDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.MONEDA
UNION
SELECT 'PAIS' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.PAIS
UNION
SELECT 'PROFESION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.PROFESION
UNION
SELECT 'PROVEEDOR' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.PROVEEDOR
UNION
SELECT 'SECTORACTIVIDAD' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.SECTORACTIVIDAD
UNION
SELECT 'TIPOFACTURA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOFACTURA
UNION
SELECT 'TIPOIMPORTE' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOIMPORTE
UNION
SELECT 'TIPOIMPUESTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOIMPUESTO
UNION
SELECT 'TIPOINSTITUCION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOINSTITUCION
UNION
SELECT 'TIPOLINEACREDITO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOLINEACREDITO
UNION
SELECT 'TIPOMARCACLASETARJETA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOMARCACLASETARJETA
UNION
SELECT 'TIPOPARENTESCO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOPARENTESCO
UNION
SELECT 'TIPOPRODUCTO' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOPRODUCTO
UNION
SELECT 'TIPOTARJETA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOTARJETA
UNION
SELECT 'TIPOTARJETABANCARIA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOTARJETABANCARIA
UNION
SELECT 'TIPOURBANIZACION' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOURBANIZACION
UNION
SELECT 'TIPOVIA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOVIA
UNION
SELECT 'TIPOVIVIENDA' AS TABLA, COUNT (*) AS CANTIDAD FROM ODS_MAESTRAS.TIPOVIVIENDA;
